server:
  port: 9000

logging:
  level:
    org.springframework.security: trace
    # 启用Druid详细日志
    com.alibaba.druid: debug
spring:
  application:
    name: snail-auth
  security:
    oauth2:
      authorizationserver:
        # 从网关访问到的具体地址
        issuer: http://192.168.5.228:9001/auth
        jks:
          path: snail-auth-server-dev.jks
          # 支持环境变量覆盖  export JKS_PASSWORD=your-production-password
          password: ${JKS_PASSWORD:snail-ken}
          alias: snail-auth-server
  # 使用druid数据源配置mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: leomaster
    password: leomastermysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.12:3306/auth?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    # Druid特有配置
    druid:
      # 初始化大小
      initial-size: 5
      # 最小连接数
      min-idle: 5
      # 最大连接数
      max-active: 20
      # 获取连接等待超时的时间
      max-wait: 60000
      # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 验证连接有效性SQL
      validation-query: SELECT 1
      # 申请连接时执行validationQuery检测连接是否有效
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.12:10000
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        metadata:
          env: dev
      config:
        enabled: false

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.haiyinlong.snail.authentication.infrastructure.dao.entity
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
